### PR TITLE
qpnp-haptic: fixed haptic strength control

### PR DESCRIPTION
**Pull request by radu-v**
This fixes the haptic feedback strength control.
Removed the `level` sys node that was redundant (we already have `vmax_mv`) and re-factored the haptic strength setting functions a bit.

### CODE REVIEW

**Comment by StollD** [comment]
What effect is this supposed to have, and why should it be added to umbrella?

Umbrella is supposed to be as close to stock as possible, so it is
* shippable with TWRP without forcing something onto the user that they don't want
* usable as an up to date base for custom (downstream) kernels, so with all updates from CAF and linux-stable already merged.

But since this isn't part of the stock kernel I am not sure if it should be added to umbrella. If this is an actual *bug* in the stock kernel, then I would be more ok with adding it here. But otherwise it should be in a downstream version of umbrella.

Also, I saw you made a `feature/kcal` branch. I would definitly not want to merge that one, for exactly those reasons.

**Comment by radu-v** [comment]
On stock it is not possible to adjust vibration strength, even when rooted, so that is a bug and this fixes it.

Regarding `feature/kcal` I agree, I actually wasn't going to create a PR for that. Do you think it's worth creating a `mod` branch, where any non-stock features would go into?

**Comment by StollD** [comment]
Yeah, that sounds like it would be something that should probably be merged.

Regarding a `mods` branch: I'd say that should be done on a different repository. That would allow you to make releases there and have a better overall seperation.

**Comment by radu-v** [comment]
fair enough. I'll re-activate my `umbrella-mod` repo then :)

**Pull request merged**
